//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SketchReinforcement.Resourses.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SketchReinforcement.Resourses.Strings.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на           Transparent background.
        /// </summary>
        public static string BackGroundColor {
            get {
                return ResourceManager.GetString("BackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External border.
        /// </summary>
        public static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder selection.
        /// </summary>
        public static string ButtonFolder {
            get {
                return ResourceManager.GetString("ButtonFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dimensions by axes.
        /// </summary>
        public static string ByAxis {
            get {
                return ResourceManager.GetString("ByAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create sketch for some partition.
        /// </summary>
        public static string ByPartition {
            get {
                return ResourceManager.GetString("ByPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create sketch for rebars of current view.
        /// </summary>
        public static string ByView {
            get {
                return ResourceManager.GetString("ByView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string CheckFolder {
            get {
                return ResourceManager.GetString("CheckFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove ALL pictures.
        /// </summary>
        public static string DeleteSketch {
            get {
                return ResourceManager.GetString("DeleteSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The project file is in a protected folder. Impossible to create a folder to place sketches..
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на        For standard shapes only.
        /// </summary>
        public static string GroupBox2 {
            get {
                return ResourceManager.GetString("GroupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sketching folder.
        /// </summary>
        public static string GroupFolder {
            get {
                return ResourceManager.GetString("GroupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на runningadd-inanditsresults.htm.
        /// </summary>
        public static string HelpSection {
            get {
                return ResourceManager.GetString("HelpSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show hooks length.
        /// </summary>
        public static string HooksVisible {
            get {
                return ResourceManager.GetString("HooksVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sketсh height.
        /// </summary>
        public static string HSketch {
            get {
                return ResourceManager.GetString("HSketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect system rebar families. Use the form of rebars of the 2016 version..
        /// </summary>
        public static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save the file before execute the command.
        /// </summary>
        public static string Info2 {
            get {
                return ResourceManager.GetString("Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font.
        /// </summary>
        public static string LabelFont {
            get {
                return ResourceManager.GetString("LabelFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum length.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reinforcement sketch.
        /// </summary>
        public static string NameImage {
            get {
                return ResourceManager.GetString("NameImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reinforcement: tools.
        /// </summary>
        public static string NamePanel {
            get {
                return ResourceManager.GetString("NamePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reinforcement sketch.
        /// </summary>
        public static string NameTransaction {
            get {
                return ResourceManager.GetString("NameTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove sketch.
        /// </summary>
        public static string NameTransaction1 {
            get {
                return ResourceManager.GetString("NameTransaction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create sketch for tag.
        /// </summary>
        public static string NameTransaction2 {
            get {
                return ResourceManager.GetString("NameTransaction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overlap.
        /// </summary>
        public static string Overlap {
            get {
                return ResourceManager.GetString("Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \\Resources\\Help\\Sketch reinforcement.chm.
        /// </summary>
        public static string pathToHelp {
            get {
                return ResourceManager.GetString("pathToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c:\\ProgramData\\Autodesk\\ApplicationPlugins\\ADNPlugin-SketchReinforcement.bundle\\Contents\\Resources\\Help\\Sketch reinforcement.chm.
        /// </summary>
        public static string PathToHelpFile {
            get {
                return ResourceManager.GetString("PathToHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create sketch for all rebars.
        /// </summary>
        public static string RadioSelectAll {
            get {
                return ResourceManager.GetString("RadioSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create sketch for some rebars.
        /// </summary>
        public static string RadioSelectSingle {
            get {
                return ResourceManager.GetString("RadioSelectSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw bending radius.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Draw bending radius.
        /// </summary>
        public static string RadiusBending {
            get {
                return ResourceManager.GetString("RadiusBending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select single rebar.
        /// </summary>
        public static string SelectRebar {
            get {
                return ResourceManager.GetString("SelectRebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select reinforcement tags.
        /// </summary>
        public static string SelectTags {
            get {
                return ResourceManager.GetString("SelectTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Offset from line.
        /// </summary>
        public static string ShiftFromLine {
            get {
                return ResourceManager.GetString("ShiftFromLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на           Show bend angle.
        /// </summary>
        public static string ShowAngle {
            get {
                return ResourceManager.GetString("ShowAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show dimension lines.
        /// </summary>
        public static string ShowDimLines {
            get {
                return ResourceManager.GetString("ShowDimLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard shape.
        /// </summary>
        public static string TabControl1 {
            get {
                return ResourceManager.GetString("TabControl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project shape.
        /// </summary>
        public static string TabControl2 {
            get {
                return ResourceManager.GetString("TabControl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на problem.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preview sketch.
        /// </summary>
        public static string TitleFormPreview {
            get {
                return ResourceManager.GetString("TitleFormPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update manual correction.
        /// </summary>
        public static string UpdateManual {
            get {
                return ResourceManager.GetString("UpdateManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add-in is for version not older then 2023.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string Warning1 {
            get {
                return ResourceManager.GetString("Warning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No family found for creating sketches-tags. Creating sketches for this project is not possible. Send a request to the developers (office@ar-cadia.com.ua) to solve the problem..
        /// </summary>
        public static string Warning2 {
            get {
                return ResourceManager.GetString("Warning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No suitable tags for sketching reinforcement or no need for changes. Or not the right active view..
        /// </summary>
        public static string Warning3 {
            get {
                return ResourceManager.GetString("Warning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Performs processing of existing tags....
        /// </summary>
        public static string WorkProcess1 {
            get {
                return ResourceManager.GetString("WorkProcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Performs processing of views....
        /// </summary>
        public static string WorkProcess2 {
            get {
                return ResourceManager.GetString("WorkProcess2", resourceCulture);
            }
        }
    }
}
